export const GENRES = [
  "Soca",
  "Afrobeats",
  "Dancehall",
  "RnB",
  "Throwbacks",
  "Reggae",
  "Gospel",
] as const;

export type Genre = (typeof GENRES)[number];

export const GENRE_COLOURS: Record<Genre, string> = {
  Soca: "#f59e0b",
  Afrobeats: "#a855f7",
  Dancehall: "#22c55e",
  RnB: "#ef4444",
  Throwbacks: "#3b82f6",
  Reggae: "#10b981",
  Gospel: "#eab308",
};

export type Song = {
  title: string;
  artist: string;
};

export type Medley = {
  name: string;
  genre: Genre;
  songs: Song[];
  soundcloudUrl?: string;
};

export const MEDLEYS: Medley[] = [
  {
    name: "Soca Entry",
    genre: "Soca",
    songs: [
      { title: "Hot Hot Hot", artist: "Arrow" },
      { title: "Nani Whine", artist: "Crazy" },
      { title: "Dollar Whine", artist: "Mr. Vegas / Collin Lucas" },
      { title: "Holiday", artist: "Problem Child" },
      { title: "Mind Your Funky Business", artist: "Fimba" },
      { title: "Mind My Business", artist: "Patrice Roberts" },
      { title: "Run Wid It", artist: "Mr. Killa" },
      { title: "Follow Da Leader", artist: "The Soca Boys" },
      { title: "It's Carnival", artist: "Machel Montano" },
      { title: "Jump", artist: "Rupee" },
      { title: "Famalay", artist: "Skinny Fabulous, Machel Montano & Bunji Garlin" },
    ],
  },
  {
    name: "Love the Afro (2024)",
    genre: "Afrobeats",
    songs: [
      { title: "Love Me JeJe", artist: "Tems" },
      { title: "Soh Soh", artist: "Odeal" },
      { title: "Essence", artist: "Wizkid ft. Tems" },
      { title: "Monalisa", artist: "Lojay & Sarz" },
      { title: "Yahyuppiyah", artist: "Uncle Waffles, Tony Duardo & Justin99 ft. Pcee, EeQue & Chley" },
      { title: "Unavailable", artist: "Davido ft. Musa Keys" },
      { title: "Anybody", artist: "Burna Boy" },
    ],
  },
  {
    name: "Original Dancehall (2024)",
    genre: "Dancehall",
    songs: [
      { title: "Jump", artist: "Tyla" },
      { title: "Bubble Gum", artist: "Valiant" },
      { title: "Continental", artist: "Nigy Boy" },
      { title: "Talibans II", artist: "Byron Messia & Burna Boy" },
      { title: "Drift", artist: "Teejay" },
      { title: "Ravers Gas", artist: "Ding Dong" },
      { title: "Ambala", artist: "Squash" },
      { title: "Mad Out", artist: "Valiant" },
      { title: "Crocodile Teeth", artist: "Skillibeng" },
      { title: "Speed Off", artist: "Valiant" },
      { title: "Verified Choppa 2", artist: "Marksman" },
      { title: "Brrp", artist: "Skeng" },
    ],
  },
  {
    name: "Nostalgia (UK Throwbacks)",
    genre: "Throwbacks",
    songs: [
      { title: "Fireflies", artist: "Owl City" },
      { title: "A Thousand Years", artist: "Christina Perri" },
      { title: "Year 3000", artist: "Busted" },
      { title: "Wannabe", artist: "Spice Girls" },
      { title: "Rock DJ", artist: "Robbie Williams" },
      { title: "Murder on the Dancefloor", artist: "Sophie Ellis-Bextor" },
      { title: "Spinning Around", artist: "Kylie Minogue" },
      { title: "Don't Stop the Music", artist: "Rihanna" },
      { title: "Closer", artist: "Ne-Yo" },
      { title: "Bonkers", artist: "Dizzee Rascal" },
    ],
  },
  {
    name: "Afrobeats Medley",
    genre: "Afrobeats",
    songs: [
      { title: "Mood", artist: "Wizkid ft. BNXN" },
      { title: "Kilometre", artist: "Burna Boy" },
      { title: "Dumebi", artist: "Rema" },
      { title: "Kelebu", artist: "Rema" },
      { title: "Ozeba", artist: "Rema" },
    ],
  },
  {
    name: "Just Dance (90s/00s Dance)",
    genre: "Throwbacks",
    songs: [
      { title: "Whoomp! (There It Is)", artist: "Tag Team" },
      { title: "Gonna Make You Sweat (Everybody Dance Now)", artist: "C+C Music Factory" },
      { title: "I'm Every Woman", artist: "Whitney Houston" },
      { title: "Free", artist: "Ultra Nate" },
      { title: "Red Alert", artist: "Basement Jaxx" },
      { title: "Believe", artist: "Cher" },
      { title: "Lola's Theme", artist: "The Shapeshifters" },
      { title: "Lady (Hear Me Tonight)", artist: "Modjo" },
      { title: "Make Luv", artist: "Room 5 ft. Oliver Cheatham" },
      { title: "I'm Too Sexy", artist: "Right Said Fred" },
      { title: "I Like to Move It", artist: "Reel 2 Real ft. The Mad Stuntman" },
      { title: "Macarena", artist: "Los Del Rio" },
      { title: "U Can't Touch This", artist: "MC Hammer" },
      { title: "Everybody (Backstreet's Back)", artist: "Backstreet Boys" },
      { title: "Move Your Feet", artist: "Junior Senior" },
      { title: "The Weekend", artist: "Michael Gray" },
      { title: "I'm Horny", artist: "Mousse T. vs Hot 'n' Juicy" },
      { title: "Finally", artist: "CeCe Peniston" },
    ],
  },
  {
    name: "Channel Surf (Theme Tunes)",
    genre: "Throwbacks",
    soundcloudUrl: "https://soundcloud.com/lme-band/channel-surf-90s-00s-theme-tunes",
    songs: [
      { title: "The Story of Tracy Beaker", artist: "Keisha White" },
      { title: "SpongeBob SquarePants Theme", artist: "SpongeBob SquarePants" },
      { title: "Proud Family Theme", artist: "Solange" },
      { title: "One on One Theme", artist: "" },
      { title: "Fresh Prince of Bel-Air Theme", artist: "DJ Jazzy Jeff & The Fresh Prince" },
      { title: "That's So Raven Theme", artist: "Raven-Symone" },
    ],
  },
  {
    name: "Evolution of Music (70s to 10s)",
    genre: "Throwbacks",
    songs: [
      { title: "I Will Survive", artist: "Gloria Gaynor" },
      { title: "Boogie Wonderland", artist: "Earth, Wind & Fire" },
      { title: "September", artist: "Earth, Wind & Fire" },
      { title: "Outstanding", artist: "The Gap Band" },
      { title: "Careless Whisper", artist: "George Michael" },
      { title: "Every Little Step", artist: "Bobby Brown" },
      { title: "Remember the Time", artist: "Michael Jackson" },
      { title: "Poison", artist: "Bell Biv DeVoe" },
      { title: "1, 2 Step", artist: "Ciara ft. Missy Elliott" },
      { title: "Get Right", artist: "Jennifer Lopez" },
      { title: "When I See You", artist: "Fantasia" },
    ],
  },
  {
    name: "RnB",
    genre: "RnB",
    songs: [
      { title: "Rock the Boat", artist: "Aaliyah" },
      { title: "Ascension (Don't Ever Wonder)", artist: "Maxwell" },
      { title: "You Are My Starship", artist: "Dazz Band" },
      { title: "Cater 2 U", artist: "Destiny's Child" },
      { title: "Until the End of Time", artist: "Justin Timberlake ft. Beyonce" },
      { title: "Can We Talk", artist: "Tevin Campbell" },
      { title: "Don't Walk Away", artist: "Jade" },
    ],
  },
  {
    name: "Lovers Lane (Reggae)",
    genre: "Reggae",
    songs: [
      { title: "Smile Jamaica", artist: "Chronixx" },
      { title: "Love Doctor", artist: "Romain Virgo" },
      { title: "Main Squeeze", artist: "Lloyd Brown" },
      { title: "She's Royal", artist: "Tarrus Riley" },
      { title: "The Girl Is Mine", artist: "Morgan Heritage" },
      { title: "Rock Away", artist: "Beres Hammond" },
      { title: "Silly Games", artist: "Janet Kay" },
      { title: "Too Experienced", artist: "Barrington Levy" },
      { title: "Substitute Lover", artist: "Half Pint" },
      { title: "Blessings (When a Man Loves a Woman)", artist: "Christopher Martin" },
    ],
  },
  {
    name: "Gospel Entry",
    genre: "Gospel",
    songs: [
      { title: "Looking for You", artist: "Kirk Franklin" },
      { title: "When Jesus Says Yes", artist: "Michelle Williams" },
      { title: "Wish Somebody's Soul Would Catch on Fire", artist: "The Spirituals / traditional gospel" },
    ],
  },
  {
    name: "CD Burn Unit (2000s RnB)",
    genre: "RnB",
    soundcloudUrl: "https://soundcloud.com/lme-band/cd-burn-unit-00s-mix-chelsies-bday-party",
    songs: [
      { title: "Single Ladies", artist: "Beyonce" },
      { title: "What's My Name?", artist: "Rihanna ft. Drake" },
      { title: "Drop It Like It's Hot", artist: "Snoop Dogg ft. Pharrell" },
      { title: "Who's That Girl?", artist: "Eve" },
      { title: "Just a Friend 2002", artist: "Mario" },
      { title: "Foolish", artist: "Ashanti" },
      { title: "Caught Up", artist: "Usher" },
      { title: "It's Not Right but It's Okay", artist: "Whitney Houston" },
      { title: "Kiss Kiss", artist: "Chris Brown ft. T-Pain" },
      { title: "So Sick", artist: "Ne-Yo" },
      { title: "Jenny from the Block", artist: "Jennifer Lopez" },
      { title: "Independent Women", artist: "Destiny's Child" },
      { title: "Entourage", artist: "Omarion" },
    ],
  },
  {
    name: "Heavy Hitterz",
    genre: "RnB",
    soundcloudUrl: "https://soundcloud.com/lme-band/heavy-hitterz-90s-00s-mix-just-dance",
    songs: [
      { title: "Love Like This", artist: "Faith Evans" },
      { title: "Crazy in Love", artist: "Beyonce ft. Jay-Z" },
      { title: "1 Thing", artist: "Amerie" },
      { title: "Scandalous", artist: "Mis-Teeq" },
      { title: "Dirrty", artist: "Christina Aguilera" },
      { title: "Show Me What You Got", artist: "Jay-Z" },
      { title: "This Is How We Do It", artist: "Montell Jordan" },
      { title: "Let It Go", artist: "Keyshia Cole ft. Missy Elliott & Lil Kim" },
      { title: "Return of the Mack", artist: "Mark Morrison" },
      { title: "Nuthin' but a 'G' Thang", artist: "Dr. Dre ft. Snoop Doggy Dogg" },
      { title: "Freak Like Me", artist: "Adina Howard" },
      { title: "Freak Like Me", artist: "Sugababes" },
      { title: "Thong Song", artist: "Sisqo" },
      { title: "In the Morning", artist: "Egypt" },
      { title: "Too Many Man", artist: "Boy Better Know" },
      { title: "Head, Shoulders, Knees & Toes", artist: "KSI, S-X, Tion Wayne & Bugzy Malone" },
      { title: "Migraine Skank", artist: "Gracious K" },
    ],
  },
  {
    name: "Caribbean Way",
    genre: "Dancehall",
    songs: [
      { title: "Welcome to Jamrock", artist: "Damian Marley" },
      { title: "I'm Still in Love with You", artist: "Sean Paul ft. Sasha" },
      { title: "Heads High", artist: "Mr. Vegas" },
      { title: "Romie", artist: "Beenie Man" },
      { title: "No, No, No", artist: "Dawn Penn" },
      { title: "Can't Satisfy Her", artist: "I Wayne" },
      { title: "Too Experienced", artist: "Barrington Levy" },
      { title: "I Was Born a Winner", artist: "Freddie McGregor" },
      { title: "I Am Blessed", artist: "Mr. Vegas" },
      { title: "Everyone Falls in Love", artist: "Tanto Metro & Devonte" },
      { title: "Basement Party", artist: "Rayvon" },
      { title: "Dancehall Queen", artist: "Beenie Man ft. Chevelle Franklin" },
      { title: "So Special", artist: "Mavado" },
      { title: "Hope and Pray", artist: "Mavado" },
      { title: "Rum and RedBull", artist: "Beenie Man ft. Future Fambo" },
      { title: "Pon de River, Pon de Bank", artist: "Elephant Man" },
      { title: "It's Raining", artist: "Marvia Providence" },
      { title: "Hear My Cry O Lord", artist: "Marvia Providence" },
      { title: "Bun Bad Mind", artist: "Elephant Man" },
      { title: "Weh Dem a Do", artist: "Mavado" },
      { title: "Signal Di Plane", artist: "Elephant Man" },
      { title: "Willie Bounce", artist: "Elephant Man" },
      { title: "Wacky Dip", artist: "Voicemail" },
      { title: "Step Out", artist: "Busy Signal" },
      { title: "Tuck in Yuh Belly", artist: "Leftside" },
      { title: "Tight Up Skirt", artist: "Red Rat" },
      { title: "Goodas Mi Back", artist: "Tony Matterhorn" },
      { title: "Dutty Wine", artist: "Tony Matterhorn" },
      { title: "Hot Wuk", artist: "Mr. Vegas" },
      { title: "When You Feel Lonely", artist: "Mavado" },
      { title: "Come Into My Room", artist: "Mavado" },
    ],
  },
  {
    name: "Cassette Culture",
    genre: "Throwbacks",
    songs: [
      { title: "Right Here", artist: "SWV" },
      { title: "Optimistic", artist: "Sounds of Blackness" },
      { title: "Back to Life", artist: "Soul II Soul" },
      { title: "Scream", artist: "Michael Jackson & Janet Jackson" },
      { title: "I Wanna Be Down", artist: "Brandy" },
      { title: "Back & Forth", artist: "Aaliyah" },
      { title: "Just Friends (Sunny)", artist: "Musiq Soulchild" },
      { title: "U Know What's Up", artist: "Donell Jones" },
      { title: "Doo Wop (That Thing)", artist: "Lauryn Hill" },
      { title: "Juicy", artist: "The Notorious B.I.G." },
      { title: "California Love", artist: "2Pac ft. Dr. Dre" },
      { title: "Summertime", artist: "DJ Jazzy Jeff & The Fresh Prince" },
      { title: "Real Love", artist: "Mary J. Blige" },
      { title: "Family Affair", artist: "Mary J. Blige" },
    ],
  },
  {
    name: "2025 Highlights",
    genre: "Throwbacks",
    songs: [
      { title: "Real Love", artist: "Mary J. Blige" },
      { title: "Cardboard Box", artist: "FLO" },
      { title: "Not Like Us", artist: "Kendrick Lamar" },
      { title: "Folded", artist: "Kehlani" },
      { title: "Snooze", artist: "SZA" },
      { title: "Do What I Say", artist: "KWN" },
      { title: "MUTT", artist: "Leon Thomas" },
      { title: "KARMA", artist: "Wizkid" },
      { title: "Clarks", artist: "Vybz Kartel ft. Popcaan & Gaza Slim" },
      { title: "Soh Soh", artist: "Odeal" },
      { title: "Like2", artist: "CallMeTheKidd" },
    ],
  },
  {
    name: "GBNF BET Awards Style",
    genre: "RnB",
    songs: [
      { title: "Thriller", artist: "Michael Jackson" },
      { title: "Don't Stop 'Til You Get Enough", artist: "Michael Jackson" },
      { title: "I Wanna Thank Ya", artist: "Angie Stone ft. Snoop Dogg" },
      { title: "Wish I Didn't Miss You", artist: "Angie Stone" },
      { title: "Saving All My Love for You", artist: "Whitney Houston" },
      { title: "Never Too Much", artist: "Luther Vandross" },
    ],
  },
  {
    name: "Burna / Rema / Afro 25",
    genre: "Afrobeats",
    songs: [
      { title: "Kilometre", artist: "Burna Boy" },
      { title: "Dumebi", artist: "Rema" },
      { title: "Kelebu", artist: "Rema" },
      { title: "Ozeba", artist: "Rema" },
    ],
  },
  {
    name: "Big Dansa (Soca 25)",
    genre: "Soca",
    songs: [
      { title: "Year for Love", artist: "Voice" },
      { title: "The Greatest Bend Over", artist: "Yung Bredda" },
      { title: "Brain Freeze", artist: "Leadpipe & Saddis" },
      { title: "Cheers to Life", artist: "Voice" },
      { title: "Dansa", artist: "Klassik Frescobar" },
      { title: "Kick in She Back Doh", artist: "Burning Flames" },
      { title: "Do What You Want", artist: "Skinny Fabulous" },
      { title: "Wete Fete", artist: "Asa Bantan" },
      { title: "In the Water", artist: "Suh Raw" },
      { title: "Pump Yuh Flag", artist: "Machel Montano" },
    ],
  },
];
